${form.getError("name")}
${form.getError("email")}
${form.getError("email2")}
${form.getError("password")}
${form.getError("ipv4")}
${form.getError("ipv6")}
${form.getError("phone")}
${form.getError("fax")}
${form.getError("regex")}