name: GitHub Maven Build

on: [push]

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install with Maven
        run: mvn -B -Dmaven.test.skip=true clean install --file pom.xml
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
