name: GitHub Maven Build

on: [push]

jobs:
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
